#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This makes it easier for users to
# see which command caused the error.
F=$@
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
cd $HOME/sbitx-ham-apps
git stash --include-untracked
git pull
chmod +x *
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

echo "sbitx ham apps has been updated. You can now close this window."
